name: flutter_midi
description: A Flutter Plugin to Play midi on iOS and Android.
version: 1.0.2
author: Rody Davis <rody.davis.jr@gmail.com>
homepage: https://github.com/rodydavis/flutter_midi
publish_to: none

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_midi_platform_interface:
    git:
      url: git@github.com:mdccxv/flutter_midi.git
      ref: temp-support
      path: flutter_midi_platform_interface
  meta: ^1.0.5
  path_provider: ^2.0.1
  path_provider_macos: ^2.0.0
  plugin_platform_interface: ^2.0.0

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: FlutterMidiPlugin
      android:
        package: com.appleeducate.fluttermidi
        pluginClass: FlutterMidiPlugin
      # web:
      #   default_package: flutter_midi_web
      # macos:
      #   pluginClass: FlutterMidiPlugin
dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.3
  test: ^1.16.0

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.8 <2.0.0"
